# Generated by Django 3.0.7 on 2020-06-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('fdc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='N/A', max_length=200, unique=True)),
                ('kcal', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('water', models.FloatField()),
                ('calcium', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('potassium', models.FloatField()),
            ],
        ),
    ]
